### ISSUE TITLE
Transmission 2.82 or 2.84 can't be compiled again

### ISSUE THREAD

**Issue by GoogleCodeExporter** [wydevices/wydevices#20]
```
What steps will reproduce the problem?
1. Try to compile transmission raises error

What is the expected output? What do you see instead?

compilation success, but i receive:

/usr/lib/libcurl.so: could not read symbols: File in wrong format
collect2: ld returned 1 exit status
make[1]: *** [bitfield-test] Error 1
make[1]: se sale del directorio 
`/home/wydev/COMPILESVN-RO/wydevices-read-only/packages/transmission/transmissio
n-2.84/libtransmission'
make: *** [all-recursive] Error 1




Please use labels and text to provide additional information.


```

Original issue reported on code.google.com by `roberto....@gmail.com` on 20 Feb 2015 at 9:01

**Comment by wydevices** [comment]
I think i found the problem... it was searching for /usr/lib/libcurl.so ... and i realized it was missing. If i add a symbolic link to libraries for target, it founds what it needs and works... i think.

ln -s /opt/STM/STLinux-2.3/devkit/sh4/target/usr/lib/libcurl.so.4 /usr/lib/libcurl.so

**Comment by wydevices** [comment]
it seems this is now compiling just fine
https://github.com/wydevices/wydevices/blob/cec8b8c02f45fddb9099da7f2b61d5c1d91d050a/packages/transmission/build.config
